name = "UnspecifiedTypes"
uuid = "42b3faec-625b-4613-8ddc-352bf9672b8d"
version = "0.1.9"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[compat]
julia = "1.10"
